CREATE TABLE [dbo].[GiftCards]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Code] VARCHAR(20) NOT NULL,
	[Amount] MONEY NOT NULL,
	[Created] DATETIME2 NOT NULL DEFAULT getdate(),
	[Updated] DATETIME2 NOT NULL DEFAULT getdate()
)
